# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fw.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fw.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66w.proto\x12\x07\x66wproto\"5\n\x0c\x44\x65\x63odedFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x12\n\nframe_data\x18\x02 \x01(\x0c\"i\n\x0fInferenceResult\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x19\n\x11processing_status\x18\x02 \x01(\x04\x12(\n\ndetections\x18\x03 \x03(\x0b\x32\x14.fwproto.BoundingBox\"^\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x04\x12\t\n\x01y\x18\x02 \x01(\x04\x12\n\n\x02\x64x\x18\x03 \x01(\x04\x12\n\n\x02\x64y\x18\x05 \x01(\x04\x12\r\n\x05label\x18\x06 \x01(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x02\"9\n\tRTPPacket\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08track_id\x18\x02 \x01(\t\x12\x0c\n\x04ssrc\x18\x03 \x01(\r\":\n\rStreamSummary\x12\x18\n\x10packets_received\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xb6\x01\n\x0bMetricEvent\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12,\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x1e.fwproto.MetricEvent.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xdc\x01\n\rComputeStream\x12?\n\x0cOffloadImage\x12\x15.fwproto.DecodedFrame\x1a\x18.fwproto.InferenceResult\x12?\n\x0bStreamVideo\x12\x12.fwproto.RTPPacket\x1a\x18.fwproto.InferenceResult(\x01\x30\x01\x12I\n\x12StreamDecodedVideo\x12\x15.fwproto.DecodedFrame\x1a\x18.fwproto.InferenceResult(\x01\x30\x01\x42*Z(github.com/BuzzingTaz/fw-edge-apps/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fw_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/BuzzingTaz/fw-edge-apps/proto'
  _globals['_METRICEVENT_DATAENTRY']._loaded_options = None
  _globals['_METRICEVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_DECODEDFRAME']._serialized_start=21
  _globals['_DECODEDFRAME']._serialized_end=74
  _globals['_INFERENCERESULT']._serialized_start=76
  _globals['_INFERENCERESULT']._serialized_end=181
  _globals['_BOUNDINGBOX']._serialized_start=183
  _globals['_BOUNDINGBOX']._serialized_end=277
  _globals['_RTPPACKET']._serialized_start=279
  _globals['_RTPPACKET']._serialized_end=336
  _globals['_STREAMSUMMARY']._serialized_start=338
  _globals['_STREAMSUMMARY']._serialized_end=396
  _globals['_METRICEVENT']._serialized_start=399
  _globals['_METRICEVENT']._serialized_end=581
  _globals['_METRICEVENT_DATAENTRY']._serialized_start=538
  _globals['_METRICEVENT_DATAENTRY']._serialized_end=581
  _globals['_COMPUTESTREAM']._serialized_start=584
  _globals['_COMPUTESTREAM']._serialized_end=804
# @@protoc_insertion_point(module_scope)
