# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fw_pb2 as fw__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fw_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputeStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OffloadImage = channel.unary_unary(
                '/fwproto.ComputeStream/OffloadImage',
                request_serializer=fw__pb2.DecodedFrame.SerializeToString,
                response_deserializer=fw__pb2.InferenceResult.FromString,
                _registered_method=True)
        self.StreamVideo = channel.stream_stream(
                '/fwproto.ComputeStream/StreamVideo',
                request_serializer=fw__pb2.RTPPacket.SerializeToString,
                response_deserializer=fw__pb2.InferenceResult.FromString,
                _registered_method=True)
        self.StreamDecodedVideo = channel.stream_stream(
                '/fwproto.ComputeStream/StreamDecodedVideo',
                request_serializer=fw__pb2.DecodedFrame.SerializeToString,
                response_deserializer=fw__pb2.InferenceResult.FromString,
                _registered_method=True)


class ComputeStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OffloadImage(self, request, context):
        """Basic implementation for one frame at a time
        Recommended to use streams for larger images
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVideo(self, request_iterator, context):
        """The client streams RTP packets to the server, receives a stream of corresponding inference results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDecodedVideo(self, request_iterator, context):
        """Alternate path to stream decoded video directly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OffloadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.OffloadImage,
                    request_deserializer=fw__pb2.DecodedFrame.FromString,
                    response_serializer=fw__pb2.InferenceResult.SerializeToString,
            ),
            'StreamVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=fw__pb2.RTPPacket.FromString,
                    response_serializer=fw__pb2.InferenceResult.SerializeToString,
            ),
            'StreamDecodedVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDecodedVideo,
                    request_deserializer=fw__pb2.DecodedFrame.FromString,
                    response_serializer=fw__pb2.InferenceResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fwproto.ComputeStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fwproto.ComputeStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputeStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OffloadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fwproto.ComputeStream/OffloadImage',
            fw__pb2.DecodedFrame.SerializeToString,
            fw__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fwproto.ComputeStream/StreamVideo',
            fw__pb2.RTPPacket.SerializeToString,
            fw__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDecodedVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fwproto.ComputeStream/StreamDecodedVideo',
            fw__pb2.DecodedFrame.SerializeToString,
            fw__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
