// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/fw.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FrameData     []byte                 `protobuf:"bytes,2,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedFrame) Reset() {
	*x = DecodedFrame{}
	mi := &file_proto_fw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedFrame) ProtoMessage() {}

func (x *DecodedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedFrame.ProtoReflect.Descriptor instead.
func (*DecodedFrame) Descriptor() ([]byte, []int) {
	return file_proto_fw_proto_rawDescGZIP(), []int{0}
}

func (x *DecodedFrame) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DecodedFrame) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

type InferenceResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timestamp        uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessingStatus uint64                 `protobuf:"varint,2,opt,name=processing_status,json=processingStatus,proto3" json:"processing_status,omitempty"`
	Detections       []*BoundingBox         `protobuf:"bytes,3,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InferenceResult) Reset() {
	*x = InferenceResult{}
	mi := &file_proto_fw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResult) ProtoMessage() {}

func (x *InferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResult.ProtoReflect.Descriptor instead.
func (*InferenceResult) Descriptor() ([]byte, []int) {
	return file_proto_fw_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResult) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InferenceResult) GetProcessingStatus() uint64 {
	if x != nil {
		return x.ProcessingStatus
	}
	return 0
}

func (x *InferenceResult) GetDetections() []*BoundingBox {
	if x != nil {
		return x.Detections
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint64                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint64                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Dx            uint64                 `protobuf:"varint,3,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            uint64                 `protobuf:"varint,5,opt,name=dy,proto3" json:"dy,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_proto_fw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_proto_fw_proto_rawDescGZIP(), []int{2}
}

func (x *BoundingBox) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetDx() uint64 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *BoundingBox) GetDy() uint64 {
	if x != nil {
		return x.Dy
	}
	return 0
}

func (x *BoundingBox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type RTPPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw, serialized bytes of the RTP packet
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional metadata for easy routing/logging on the server side
	TrackId       string `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Ssrc          uint32 `protobuf:"varint,3,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTPPacket) Reset() {
	*x = RTPPacket{}
	mi := &file_proto_fw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTPPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTPPacket) ProtoMessage() {}

func (x *RTPPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTPPacket.ProtoReflect.Descriptor instead.
func (*RTPPacket) Descriptor() ([]byte, []int) {
	return file_proto_fw_proto_rawDescGZIP(), []int{3}
}

func (x *RTPPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RTPPacket) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *RTPPacket) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

type StreamSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PacketsReceived int32                  `protobuf:"varint,1,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamSummary) Reset() {
	*x = StreamSummary{}
	mi := &file_proto_fw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSummary) ProtoMessage() {}

func (x *StreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSummary.ProtoReflect.Descriptor instead.
func (*StreamSummary) Descriptor() ([]byte, []int) {
	return file_proto_fw_proto_rawDescGZIP(), []int{4}
}

func (x *StreamSummary) GetPacketsReceived() int32 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *StreamSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MetricEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricEvent) Reset() {
	*x = MetricEvent{}
	mi := &file_proto_fw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricEvent) ProtoMessage() {}

func (x *MetricEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricEvent.ProtoReflect.Descriptor instead.
func (*MetricEvent) Descriptor() ([]byte, []int) {
	return file_proto_fw_proto_rawDescGZIP(), []int{5}
}

func (x *MetricEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MetricEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MetricEvent) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_fw_proto protoreflect.FileDescriptor

const file_proto_fw_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/fw.proto\x12\afwproto\"K\n" +
	"\fDecodedFrame\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x02 \x01(\fR\tframeData\"\x92\x01\n" +
	"\x0fInferenceResult\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12+\n" +
	"\x11processing_status\x18\x02 \x01(\x04R\x10processingStatus\x124\n" +
	"\n" +
	"detections\x18\x03 \x03(\v2\x14.fwproto.BoundingBoxR\n" +
	"detections\"\x7f\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x04R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x04R\x01y\x12\x0e\n" +
	"\x02dx\x18\x03 \x01(\x04R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x05 \x01(\x04R\x02dy\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\"N\n" +
	"\tRTPPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12\x12\n" +
	"\x04ssrc\x18\x03 \x01(\rR\x04ssrc\"T\n" +
	"\rStreamSummary\x12)\n" +
	"\x10packets_received\x18\x01 \x01(\x05R\x0fpacketsReceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf3\x01\n" +
	"\vMetricEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x122\n" +
	"\x04data\x18\x05 \x03(\v2\x1e.fwproto.MetricEvent.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdc\x01\n" +
	"\rComputeStream\x12?\n" +
	"\fOffloadImage\x12\x15.fwproto.DecodedFrame\x1a\x18.fwproto.InferenceResult\x12?\n" +
	"\vStreamVideo\x12\x12.fwproto.RTPPacket\x1a\x18.fwproto.InferenceResult(\x010\x01\x12I\n" +
	"\x12StreamDecodedVideo\x12\x15.fwproto.DecodedFrame\x1a\x18.fwproto.InferenceResult(\x010\x01B*Z(github.com/BuzzingTaz/fw-edge-apps/protob\x06proto3"

var (
	file_proto_fw_proto_rawDescOnce sync.Once
	file_proto_fw_proto_rawDescData []byte
)

func file_proto_fw_proto_rawDescGZIP() []byte {
	file_proto_fw_proto_rawDescOnce.Do(func() {
		file_proto_fw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fw_proto_rawDesc), len(file_proto_fw_proto_rawDesc)))
	})
	return file_proto_fw_proto_rawDescData
}

var file_proto_fw_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_fw_proto_goTypes = []any{
	(*DecodedFrame)(nil),    // 0: fwproto.DecodedFrame
	(*InferenceResult)(nil), // 1: fwproto.InferenceResult
	(*BoundingBox)(nil),     // 2: fwproto.BoundingBox
	(*RTPPacket)(nil),       // 3: fwproto.RTPPacket
	(*StreamSummary)(nil),   // 4: fwproto.StreamSummary
	(*MetricEvent)(nil),     // 5: fwproto.MetricEvent
	nil,                     // 6: fwproto.MetricEvent.DataEntry
}
var file_proto_fw_proto_depIdxs = []int32{
	2, // 0: fwproto.InferenceResult.detections:type_name -> fwproto.BoundingBox
	6, // 1: fwproto.MetricEvent.data:type_name -> fwproto.MetricEvent.DataEntry
	0, // 2: fwproto.ComputeStream.OffloadImage:input_type -> fwproto.DecodedFrame
	3, // 3: fwproto.ComputeStream.StreamVideo:input_type -> fwproto.RTPPacket
	0, // 4: fwproto.ComputeStream.StreamDecodedVideo:input_type -> fwproto.DecodedFrame
	1, // 5: fwproto.ComputeStream.OffloadImage:output_type -> fwproto.InferenceResult
	1, // 6: fwproto.ComputeStream.StreamVideo:output_type -> fwproto.InferenceResult
	1, // 7: fwproto.ComputeStream.StreamDecodedVideo:output_type -> fwproto.InferenceResult
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_fw_proto_init() }
func file_proto_fw_proto_init() {
	if File_proto_fw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fw_proto_rawDesc), len(file_proto_fw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fw_proto_goTypes,
		DependencyIndexes: file_proto_fw_proto_depIdxs,
		MessageInfos:      file_proto_fw_proto_msgTypes,
	}.Build()
	File_proto_fw_proto = out.File
	file_proto_fw_proto_goTypes = nil
	file_proto_fw_proto_depIdxs = nil
}
